### ISSUE TITLE
Fix remaining Tabler dark mode issues

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/theme-tabler#103]
Still pending:

- [x] On dashboard some text are too dark

<img width="421" alt="Screenshot 2023-07-07 at 10 17 25" src="https://github.com/Laravel-Backpack/theme-tabler/assets/44643608/bcf1b82e-5f44-489f-9e23-eef0f447c045">

<img width="423" alt="Screenshot 2023-07-07 at 10 17 33" src="https://github.com/Laravel-Backpack/theme-tabler/assets/44643608/b991da54-319e-4995-9bf8-2d9d54b64aa2">

- [ ] Make elfinder dark mode

<img width="1473" alt="Screenshot 2023-07-07 at 10 16 23" src="https://github.com/Laravel-Backpack/theme-tabler/assets/44643608/5e553ab3-5424-4144-a61e-3b20d9c3698e">

- [x] Fix z-index icon picker (on @pxpm board)

<img width="581" alt="Screenshot 2023-07-07 at 10 17 01" src="https://github.com/Laravel-Backpack/theme-tabler/assets/44643608/c59ed0c7-5aea-4a6c-ba1f-40851355826b">

- [x] Make TinyMCE dark mode

<img width="1234" alt="Screenshot 2023-07-07 at 10 20 19" src="https://github.com/Laravel-Backpack/theme-tabler/assets/44643608/335769a9-0ca4-4a33-81f8-eb44ec43f128">

- [x] Fix range color

<img width="610" alt="Screenshot 2023-07-07 at 10 23 14" src="https://github.com/Laravel-Backpack/theme-tabler/assets/44643608/b62d12a0-532b-4a5c-85c6-9a5487cedf05">

_Originally posted by @jorgetwgroup in https://github.com/Laravel-Backpack/theme-tabler/issues/101#issuecomment-1625492055_

**Comment by jorgetwgroup** [comment]
@tabacitu  Add this PR's to fix tinymce:
https://github.com/Laravel-Backpack/theme-tabler/pull/105
https://github.com/Laravel-Backpack/PRO/pull/182

**Comment by jorgetwgroup** [comment]
Add PR to fix range: https://github.com/Laravel-Backpack/theme-tabler/pull/117

**Comment by jorgetwgroup** [comment]
Start this PR's to fix elFinder

https://github.com/Laravel-Backpack/FileManager/pull/35
https://github.com/Laravel-Backpack/theme-tabler/pull/116

**Comment by jorgetwgroup** [comment]
Add PR to fix dashboard colors: https://github.com/Laravel-Backpack/theme-tabler/issues/103

**Comment by tabacitu** [comment]
ElFinder PR https://github.com/Laravel-Backpack/theme-tabler/pull/116
