### ISSUE TITLE
[Bug] Icon picker z-index on over modal

### ISSUE THREAD

**Issue by jorgetwgroup** [Laravel-Backpack/theme-tabler#104]
The icon picker have a z-index issues on modal.

![image](https://github.com/Laravel-Backpack/theme-tabler/assets/44643608/a711c43e-0dc3-4ded-8de3-92282e221ec3)

The correct z-index is:

```
.iconpicker-popover {
    z-index: 1057!important
}
```

**Comment by tabacitu** [comment]
Note: only on Tabler

**Comment by pxpm** [comment]
Fixed in https://github.com/Laravel-Backpack/PRO/pull/181
