### ISSUE TITLE
[Bug] Tabler theme needs documentation

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/theme-tabler#112]
Right now we have more documentation about the Tabler theme is [the Backpack release notes](https://backpackforlaravel.com/docs/6.x/release-notes#layouts), than we have in this project's README.

We should list all features this theme has, right in its README.

**Comment by tabacitu** [comment]
And its configs - for example https://github.com/Laravel-Backpack/theme-tabler/issues/141

**Comment by karandatwani92** [comment]
PR Submitted https://github.com/Laravel-Backpack/theme-tabler/pull/144
