### ISSUE TITLE
[Bug] Can't read text on mobile

### ISSUE THREAD

**Issue by adriallongarriu** [Laravel-Backpack/theme-tabler#119]
# Bug report

### What I did

Use `'layout' => 'horizontal_overlap',`

### What I expected to happen
Be able to read the text.

### What happened

On desktop show ok:
![image](https://github.com/Laravel-Backpack/theme-tabler/assets/20278289/665fa8f6-4f2c-4840-b503-e9db86d359a2)

but on small screens:
![image](https://github.com/Laravel-Backpack/theme-tabler/assets/20278289/8a8a4eba-2cc0-45b4-870a-7527856d78c4)

### Context to replicate the bug - Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

![image](https://github.com/Laravel-Backpack/theme-tabler/assets/20278289/ee5bc7fc-ab3f-41e5-823e-cf18edc7aaa7)

**Comment by jorgetwgroup** [comment]
Thanks for open this issue i make a test on my side and there is the issue, so i will add this to our maintenance team to be fixed.

Cheers.

**Comment by pxpm** [comment]
Hey @jorgetwgroup I am doing a cleanup of tabler issues to set it as the default theme and I was un-aware of this issue as it is also marked as handled in Defense channel. 🤷 

I see this was opened 3 days ago and I don't see it added in any project, assigned to anyone or prioritized. 
This seems to me like a bug and should have been prioritized accordingly. 

Let's please either fix it (preferably), or ask someone to have a look at it (like you did with the uploader issue). 

I added to project and assigned you 🙏 

Cheers

**Comment by jorgetwgroup** [comment]
This issues is fix on PR: https://github.com/Laravel-Backpack/theme-tabler/pull/126
