### ISSUE TITLE
[Bug] v6+tabler - Unreadable progress widget

### ISSUE THREAD

**Issue by realtebo** [Laravel-Backpack/theme-tabler#132]
# Bug report

### What I did

I added a progress to my dashboard

        $widgets['before_content'][] = [
                'type'        => 'progress',
                'class'       => 'card text-white bg-primary mb-2',
                'value'       => $classi_totali,
                'description' => 'Classi',
                'progress'    => 100- intval(100 * $classi_senza_insegnanti / $classi_totali), // integer
                'hint'        => $classi_totali .' senza insegnanti.',

        ];

### What I expected to happen

I wouldl ike something link this

![image](https://github.com/Laravel-Backpack/CRUD/assets/1268699/671581b4-baac-4998-acc6-9fd5ff008c7d)

### What happened

![image](https://github.com/Laravel-Backpack/CRUD/assets/1268699/08085db9-918e-4fb3-b747-d389871eac6b)

### What I've already tried to fix it

actually nothing

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there? 

YES

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 8.2.8 (cli) (built: Jul  4 2023 15:53:15) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.2.8, Copyright (c) Zend Technologies

### LARAVEL VERSION:
10.17.1.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.1.1
backpack/crud: 6.1.7
backpack/generators: v4.0.2
backpack/pro: 2.0.10
backpack/theme-tabler: 1.0.8
```

**Comment by pxpm** [comment]
Thanks @realtebo we may need to revisit the classes used there.

Can you please provide me the HTML it generated ? I am asking to make sure the tabler views are the ones being loaded. 

Thanks 🙏

**Comment by karandatwani92** [comment]
@pxpm I just used this widget. The cause of this is `text-white` not applied to the description

**Comment by pxpm** [comment]
Thanks for investigating this @karandatwani92 🙏 

From my memory what I recall is that `progress_white` would be a white background widget and you change the progress bar color, while in `progress` you change the background color.

https://backpackforlaravel.com/docs/6.x/base-widgets#progress-1

**Comment by karandatwani92** [comment]
PR Submitted #133

**Comment by tabacitu** [comment]
We have a working PR in https://github.com/Laravel-Backpack/theme-tabler/pull/133 so let's move the conversation there please. Thanks @realtebo
