### ISSUE TITLE
[Bug][Tabler] Register & Forgotten Password pages - polish

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/theme-tabler#14]
Instead of the current coreui-wants-to-become-tabler, let's apply the layouts and style provided by Tabler:

- https://preview.tabler.io/sign-up.html
- https://preview.tabler.io/forgot-password.html

What are we doing different, and how we make our pages look as polished as those?

**Comment by maurohmartinez** [comment]
Changes included in this [PR](https://github.com/Laravel-Backpack/theme-tabler/pull/18) since they all are related to auth pages.
