### ISSUE TITLE
Utilize View Space in V6 Tabler theme 

### ISSUE THREAD

**Issue by karandatwani92** [Laravel-Backpack/theme-tabler#141]
We need to expand and utilize the space
# V6
![image](https://github.com/Laravel-Backpack/CRUD/assets/8214221/02c30bba-4df2-4529-b9ab-f46357fc1742)
# V5
![image](https://github.com/Laravel-Backpack/CRUD/assets/8214221/537fb2e0-6b90-4707-b15c-6429de48e0bb)

**Comment by tabacitu** [comment]
Let's close this in favor of https://github.com/Laravel-Backpack/theme-tabler/issues/112 - we need better docs for the Tabler theme, for sure.
