### ISSUE TITLE
[Bug] config 'searchableTable'

### ISSUE THREAD

**Issue by smart4you** [Laravel-Backpack/theme-tabler#148]
# Bug report

### What I did

`$this->crud->setOperationSetting('searchableTable', false);`

### What I expected to happen

Field "Search" will disappear in the upper right corner

### What happened

The "Search" field did not disappear, or rather the search icon - visible
![Screenshot 2023-09-19 101624](https://github.com/Laravel-Backpack/CRUD/assets/59228744/11f37981-777c-48d7-912b-43e0005fad87)

### What I've already tried to fix it

I manually changed the `list.blader.php` template - added the condition `@if($crud->getOperationSetting('searchableTable'))` for the code block `<div class="col-sm-3"><div id="datatable_search_stack" class="mt-sm-0 mt-2 d-print-none">...</div></div>`

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

backpack/backupmanager: v5.0.0
backpack/basset: 1.2.0
backpack/crud: 6.2.0
backpack/generators: v4.0.2
backpack/langfilemanager: 5.0.0
backpack/logmanager: v5.0.0
backpack/permissionmanager: 7.0.1
backpack/pro: 2.0.11
backpack/settings: 3.1.0
backpack/theme-tabler: 1.1.0

**Comment by pxpm** [comment]
Thanks @smart4you 

Sorry this took a while to get fixed. It's done in https://github.com/Laravel-Backpack/CRUD/pull/5578

Cheers
