### ISSUE TITLE
[Bug] Nested dropdowns don't work on mobile

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/theme-tabler#149]
# Bug report

### What I did

I am 100% sure that this was working. Somehow it's not working anymore 🤡 

In fact when I opened the issue https://github.com/Laravel-Backpack/demo/issues/574#issuecomment-1717406610 to test, it was working locally and failing in our online demo like @karandatwani92 pointed out. After some updates, it's gone. 

At this moment it's not working anywhere, so I suspect we may have broken it in the meanwhile, but I've spend way more time than I would like here and still not able to find the root cause for it to fail now, so I am writing this down, maybe I have an `ha-ha` moment. 

It works just fine on CoreUI themes (v2 and v4).

In tabler the mobile menu only open the first dropdown, the nested ones when clicked just close the parent without opening the child. 

If anyone has a bright idea here, fine, otherwise I will revisit this later this week.

**Comment by StefanPrintezis** [comment]
https://github.com/Laravel-Backpack/theme-tabler/blob/main/resources/assets/js/tabler.js#L15

Probably related to `bs-auto-close` being enabled by default, since we're matching on href that would mean there are multiple active dropdowns which wouldn't work with auto-close enabled? So I'd think it's not necessarily related to mobile, but inherently so because of duplicate href.

**Comment by pxpm** [comment]
Hey @StefanPrintezis thanks for the feedback. 🙏 

What's the purpose of using the same routes multiple times? I am genuinely asking, because I usually either create operations for specific scenarios, like `user/1/activate`, or `users/blocked` (instead of adding `users?blocked=true` to activate some filter).

Let me know if you think we should handle that scenario in a different way, or if there are use cases that I am missing.

Cheers

**Comment by StefanPrintezis** [comment]
The mobile menu would be in your <aside> and the desktop menu would be in your <header>, both having the same route

**Comment by pxpm** [comment]
Thanks @StefanPrintezis for the clarification. I will investigate it and get back to you 🙏

**Comment by pxpm** [comment]
This should be fixed in 1.2.1 released earlier today. 

Sorry it took a little bit to get to fix this, hope everything is right now. 

If not, please re-open 🙏
