### ISSUE TITLE
[Bug][Tabler] Choose login view

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/theme-tabler#15]
The login page we have now is a bit underwhelming & unpolished:

<img width="1512" alt="CleanShot 2023-04-10 at 11 35 41@2x" src="https://user-images.githubusercontent.com/1032474/230865492-a440f91f-41f6-457e-ba2d-1c799ecd77f0.png">
<img width="1512" alt="CleanShot 2023-04-10 at 11 36 24@2x" src="https://user-images.githubusercontent.com/1032474/230865579-f1dd0937-ab5b-4e0e-9ade-10b892431337.png">

I think we should have a few different login views, and let the developer easily choose between them:

## Default

We use the proper classes, borders, spaces etc from https://preview.tabler.io/sign-in.html

<img width="1512" alt="CleanShot 2023-04-10 at 11 43 28@2x" src="https://user-images.githubusercontent.com/1032474/230866775-4cd09ed2-5418-49f9-af0b-e3adb74cf385.png">

## Illustration

We use the design and illustration from https://preview.tabler.io/sign-in-illustration.html

<img width="1512" alt="CleanShot 2023-04-10 at 11 43 54@2x" src="https://user-images.githubusercontent.com/1032474/230866868-86ded343-66cc-45fa-a234-6383856eb0a8.png">

## Cover

We use the design and image from https://preview.tabler.io/sign-in-cover.html (or a better image if we can find a free stock image that is better than that one)

<img width="1512" alt="CleanShot 2023-04-10 at 11 44 08@2x" src="https://user-images.githubusercontent.com/1032474/230866912-a7d0af49-e1cc-4997-a44b-07efa551150f.png">

**Comment by tabacitu** [comment]
Looking good so far! 🎉 

**Let's stop working on the `mauro` branch please** - I'm sure it'll turn into a huge PR, that is difficult to review and merge. Instead let's do feature branches. This is a separate feature. It needs a separate branch, with a separate PR. That way, everything that's unrelated to this can be reviewed and merged before.

**Comment by maurohmartinez** [comment]
> Looking good so far! 🎉
> 
> **Let's stop working on the `mauro` branch please** - I'm sure it'll turn into a huge PR, that is difficult to review and merge. Instead let's do feature branches. This is a separate feature. It needs a separate branch, with a separate PR. That way, everything that's unrelated to this can be reviewed and merged before.

@tabacitu Done! I moved this and other changes to a separated branch. Will create new branches for next issues from now on.

**Comment by tabacitu** [comment]
Done in https://github.com/Laravel-Backpack/theme-tabler/pull/18 - let's move the conversation there.
