### ISSUE TITLE
[Bug] Unable to create a directory

### ISSUE THREAD

**Issue by YevheniiVolosiuk** [Laravel-Backpack/theme-tabler#153]
# Bug report

### What I did
Installed backpack to Laravel new project

Write your answer here.

### What I expected to happen
After installation, I tried to go http://example-app.local/admin/

Write your answer here.

### What happened
I got an error:
![image](https://github.com/Laravel-Backpack/theme-tabler/assets/77569229/0271b4fe-1f2a-44ba-9959-3b2effa8e6e0)

Write your answer here.

### What I've already tried to fix it
- After reading the internet tried to change permission for folder public and storage to 775 
- Tried to use these steps doesn't help https://github.com/laravel-backpack/basset#faq 

Write your answer here.

### Context to replicate the bug - Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
Write your answer here.
### PHP VERSION:
PHP 8.2.12 (cli) (built: Oct 26 2023 17:33:49) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.12, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.12, Copyright (c), by Zend Technologies
    with Xdebug v3.2.1, Copyright (c) 2002-2023, by Derick Rethans

### LARAVEL VERSION:
10.32.1.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.2.1
backpack/crud: 6.3.0
backpack/generators: v4.0.2
backpack/theme-tabler: 1.1.1

Also using Laravel Sail for project

**Comment by jorgetwgroup** [comment]
Hi @YevheniiVolosiuk can you check about the user and group assigned to this installation, the issue look like a server configuration problem.

Thanks.

**Comment by YevheniiVolosiuk** [comment]
> Hi @YevheniiVolosiuk can you check about the user and group assigned to this installation, the issue look like a server configuration problem.
> 
> Thanks.

Hi, @jorgetwgroup thanks for pointing me where I need to try to find my answer. I use Laravel Sail and the problem was fixed with this recommendation https://github.com/laravel/sail/issues/81#issuecomment-931850333.

Thanks.
