### ISSUE TITLE
[Feature Request] Toggle button to hide menus

### ISSUE THREAD

**Issue by HeriDCLXVI** [Laravel-Backpack/theme-tabler#157]
# Feature Request

### What I am trying to achieve

![image](https://github.com/Laravel-Backpack/theme-tabler/assets/21857693/a01a4366-84b4-43cb-8785-02a576e71f99)
Toggle button to hide menus in vertical layout

### How I see it implemented

![image](https://github.com/Laravel-Backpack/theme-tabler/assets/21857693/a3d8dcb5-a2d2-4e6c-9f7e-d64cd5ba412a)
![image](https://github.com/Laravel-Backpack/theme-tabler/assets/21857693/2c831ee6-a26e-4a6f-ad00-0d0d89262aa7)
This button in CoreUI v2 & v4

**Comment by karandatwani92** [comment]
Hey @HeriDCLXVI ,

Such features are part of the themes. Core UI has it, but the Tabler theme doesn't.
https://preview.tabler.io/layout-vertical.html

This request should be handled in the [theme package](https://github.com/tabler/tabler).

Thanks for asking.
