### ISSUE TITLE
[Bug] The documentation is wrong for dashboard creation

### ISSUE THREAD

**Issue by SilverComet89** [Laravel-Backpack/theme-tabler#178]
# Bug report

I'm trying to create some custom admin pages, and was told to copy the dashboard as an example. However in the theme documentation you have this:
```
cp -i vendor/backpack/theme-tabler/resources/views/dashboard.blade.php resources/views/vendor/backpack/theme-tabler/dashboard.blade.php
```
But the `dashboard.blade.php` file doesn't exist at the source to be copied.

### What I did

Fresh install, followed instructions as the default Backpack dashboard looks broken.

### What I expected to happen

A copying of the dashboard to replace the broken black text on black background of the core dashboard.

### What happened

Error `cp: vendor/backpack/theme-tabler/resources/views/dashboard.blade.php: No such file or directory`

### What I've already tried to fix it

Went looking for the file at source but doesn't exist, can't find in theme anywhere, copying the documented Backpack dashboard to the folder specified also doesn't appear to work - nothing happens.

**Comment by jcastroa87** [comment]
Hello @SilverComet89 

Sorry, we will check docs, can you try:
```
cp -i vendor/backpack/crud/src/resources/views/ui/dashboard.blade.php resources/views/vendor/backpack/ui/dashboard.blade.php
```

Let me know if you need anything else.

Cheers.

**Comment by SilverComet89** [comment]
That gives me no change - currently looks like this:
<img width="744" alt="Screenshot 2024-04-22 at 14 03 03" src="https://github.com/Laravel-Backpack/theme-tabler/assets/6968171/56ec84fc-10f5-46b2-81de-dc53604e3b0d">

**Comment by jcastroa87** [comment]
DId you customize the file? can you share the content of file with me please.

Thanks.

**Comment by SilverComet89** [comment]
That was the key I think - sorry.
```
cp -i vendor/backpack/crud/src/resources/views/ui/dashboard.blade.php resources/views/vendor/backpack/ui/dashboard.blade.php
```

does work - though the text being black on black in light mode is pretty rough, I needed to update the content of `@content`.

So to summarise - the issues that remain are:
- The source file in the documentation does not exist at that path.
- The source file when copied in is black text on black when using the "light" mode.

**Comment by jcastroa87** [comment]
Thanks i will take action on this bug.

Cheers.

**Comment by jcastroa87** [comment]
Hello @SilverComet89 light mode problem will be fixed with this PR https://github.com/Laravel-Backpack/theme-tabler/pull/179

Cheers.

**Comment by jcastroa87** [comment]
Command issue will be fixed in this https://github.com/Laravel-Backpack/theme-tabler/pull/180

I will close the issue, but please feel free to re-open or create a new one if needed.

Cheers.
