### ISSUE TITLE
[Feature Request] Slim sidemeu

### ISSUE THREAD

**Issue by malek77z** [Laravel-Backpack/theme-tabler#186]
# Feature Request/ Slim Side Menu

Slim side menu. It would be fantastic if the vertical side menu collapsed (if option enabled) into a slim icon on menu.

### What I am trying to achieve

This would be a great UX and help give as much of the page to the main CRUD

### How I see it implemented

I see it as being a optional width trigger and would be for smaller screens, but then on even small screens collapse as currently into the current hamburger menu

Here are some examples:

https://getbootstrap.com/docs/5.3/examples/sidebars/

https://usercontent.mdbootstrap.com/mdb-images/support/582c9113-cdf2-4443-84c4-fb3576d79bb4-SideBar.jpg

**Comment by jcastroa87** [comment]
Hello @malek77z 

Since the theme tabler does not have this functionality, I see it difficult to add it, since we try to keep the original as clean as possible so that it is easy to customize.

Cheers.

**Comment by malek77z** [comment]
Thanks, that makes sense, but just in case it helps anyone I made this (hacky) style that works well..

`<style>
    @media (max-width: 991px), (min-width: 1201px) {
        .d-slim{
            display: none;
        }
    }

    @media (min-width: 992px) and (max-width: 1200px) {

        .slim-lg .navbar-nav{
            padding-top: 0px !important;
        }

        .slim-lg .navbar-brand{
            padding:0px !important ;
        }
        .slim-lg {
            width: 72px !important;
            overflow: hidden;
            overflow-y: hidden !important;
        }

        .slim-lg .nav-item{
            width: 72px !important;
            overflow: hidden;
            
            margin-top: 0 !important;
            margin-bottom: 0 !important;
            margin-top: 1px;
            margin-bottom: 1px;
            border-radius: 0px;
            
        }

        .slim-lg .nav-item a{
            padding: 15px 20px !important;
        }
        .navbar-expand-lg.navbar-vertical~.navbar,
        .navbar-expand-lg.navbar-vertical~.page-wrapper {
            margin-left: 72px !important;
        }


        .slim-lg .nav-icon{
            display: block !important;
            font-size: 32px !important;
        }

        .slim-lg .nav-link.active{
            background-color: var(--tblr-navbar-active-border-color) !important;
            border-radius: 0px;
            color: var(--tblr-primary-fg) !important;
        }

        .slim-lg  .nav-item.active:after{
            display: none;
        }


        .slim-lg .nav-link span{
            display: none !important;
        }

        .slim-lg .nav-separator{
            display: none;
        }

        .d-slim-none{
            display: none;
        }

    }
</style>`

All that you need to do to apply is ass `slim-lg` to the `navbar` and it will make the icons the nav etc etc

**Comment by jcastroa87** [comment]
Great @malek77z 

Thanks for sharing this. I will close the issue, but please feel free to re-open or create a new one if needed.

Thanks again.

Cheer.
