### ISSUE TITLE
[Bug] Transparent alert widget

### ISSUE THREAD

**Issue by misiekch** [Laravel-Backpack/theme-tabler#188]
# Bug report

### What I did

After updating ```backpack/theme-tabler``` from version 1.2.0 to 1.2.11 the alert background became transparent.

In the latest release (1.2.11) the following lines have been added in the ```resources/assets/css/style.css``` file:
```
.alert {
    background: var(--tblr-surface);
}
```

The problem is that "--tblr-surface" is not defined.

This problem also occurs in the official Backpack [demo](https://demo.backpackforlaravel.com/admin/dashboard) (dashboard alert above pie charts).

### Context to replicate the bug - Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
8.2.22

### LARAVEL VERSION:
10.48.20.0

### BACKPACK PACKAGE VERSIONS:
backpack/activity-log: 2.0.5
backpack/basset: 1.3.5
backpack/crud: 6.7.30
backpack/generators: v4.0.5
backpack/permissionmanager: 7.2.1
backpack/pro: 2.2.14
backpack/settings: 3.1.1
backpack/theme-tabler: 1.2.11
```

**Comment by karandatwani92** [comment]
Thanks @misiekch, for pointing this out.

![Screenshot 2024-08-20 at 9 19 45 PM](https://github.com/user-attachments/assets/e3e0c698-2738-462b-ba23-a1aa0917a49c)

**Comment by pxpm** [comment]
Thanks for the report @misiekch a `composer update` should get you the fix 👍 

Cheers
