### ISSUE TITLE
[Bug] Tabler theme Illustration not working

### ISSUE THREAD

**Issue by munjaldevelopment** [Laravel-Backpack/theme-tabler#193]
# Bug report

### What I did

?? Change theme to tabler & auth layout 'illustration'

### What I expected to happen

?? Login page image should open

### What happened

?? Image not loading
https://preview.tabler.io/static/illustrations/undraw_secure_login_pdn4.svg

### What I've already tried to fix it

??

### Is it a bug in the latest version of Backpack?
Yes

After I run ```composer update backpack/crud``` the bug... is it still there?
Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
8.2.19

### PHP EXTENSIONS:
Core, bcmath, calendar, ctype, date, filter, hash, iconv, json, SPL, pcre, random, readline, Reflection, session, standard, mysqlnd, tokenizer, zlib, libxml, dom, PDO, openssl, SimpleXML, xml, xmlreader, xmlwriter, ldap, curl, com_dotnet, fileinfo, gd, gettext, gmp, intl, imap, mbstring, exif, mysqli, Phar, pdo_mysql, pdo_sqlite, soap, sockets, sodium, sqlite3, xsl, zip, Zend OPcache, xdebug

### LARAVEL VERSION:
11.29.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/activity-log: 2.0.6
backpack/backupmanager: v5.0.5
backpack/basset: 1.3.6
backpack/crud: 6.7.41
backpack/editable-columns: 3.0.10
backpack/filemanager: 3.0.8
backpack/generators: v4.0.7
backpack/logmanager: v5.0.2
backpack/medialibrary-uploaders: 1.2.1
backpack/menucrud: v4.0.2
backpack/newscrud: 5.1.0
backpack/pagemanager: 3.3.2
backpack/permissionmanager: 7.2.1
backpack/pro: 2.2.21
backpack/revise-operation: 2.0.0
backpack/settings: 3.1.1
backpack/theme-coreuiv2: 1.2.6
backpack/theme-coreuiv4: 1.1.4
backpack/theme-tabler: 1.2.14

**Comment by pxpm** [comment]
Thanks for the report @munjaldevelopment and for the fix @karandatwani92 

Just released a new version o theme-tabler with the fix 👍 

Cheeers
