### ISSUE TITLE
[Bug] issue loading table  spinner

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/theme-tabler#24]
When loading a table, the spinner (loading state indicator) is not properly working.

![image](https://user-images.githubusercontent.com/7188159/234547592-d51bc9f3-de42-4a8f-9896-37c9a798423d.png)

**Comment by maurohmartinez** [comment]
@pxpm were you testing this one with `crud v6` branch? We now load the spinner using @basset as you can see here `src/resources/views/crud/inc/datatables_logic.blade.php:16`
