### ISSUE TITLE
[Bug] In login page, tab from email input does not go to input password

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/theme-tabler#30]
I am used to write `email >> tab >> write password`. The fact that the recover password link is in the middle of the inputs makes me do two tabs to go from `email > password`

I suggest we move it under the password field. 

![image](https://user-images.githubusercontent.com/7188159/234828701-42e158d6-2ab9-4554-b44c-3ad04a2015a9.png)

**Comment by maurohmartinez** [comment]
@pxpm I fixed this by using `indextab`, that way we don't need to mess with Tabler's original design.

https://github.com/Laravel-Backpack/demo/pull/504
https://github.com/Laravel-Backpack/theme-tabler/pull/32

Hope that's ok.

**Comment by pxpm** [comment]
This is **not** ok, I am sorry guys 💔 

This makes navigation with keyboard completely broken. 

Email > Tab > Password > Tab > Submit button 👀 ? After this point you know something is broken on that page.

If from `Password` I want to submit the form I can press the `Enter` key. Otherwise I could just be skipping both inputs to reach the `Forgot Password` link or the `Remember Me` box, and it just looks weird that from password I go to `Login Button` skipping the `Remember Me` and `Forgot Password` link.

How I am supposed to click on the `Forgot Password` if I don't want to submit the form ? 

Email> Tab > Password > Tab > Login Button > Tab > Change Dark Mode (wtf 🙃 ) > Tab > Finally `Forgot Password`. 

Can you imagine having both inputs already pre-populated by Chrome or something, and want to click the `Remember Me` box ? 😈 

Previous: 
![image](https://user-images.githubusercontent.com/7188159/235724246-b9746735-dccd-48ef-8183-549be30f59dd.png)

Current:
![image](https://user-images.githubusercontent.com/7188159/235724442-a1262363-4114-4f0f-b0e4-e9f581d12a99.png)

I don't think we can get way without changing default Tabler layout. For that to happen we need to either:
a) accept login behaviour change to be `Email > Forgot Link > Password` instead of the current `Email > Password`
b) use the `tabindex` trick (I am not 100% convinced about it) to make it `Email > Password > Forgot Link`

@tabacitu what do you think ?

**Comment by tabacitu** [comment]
I have an opinion but won’t say it. Please figure it out together, make a decision you’re both ok with, and roll with it. 

Why? I’ll be blunt: I want to discourage you guys from bringing issues this small to me. If I handle small issues like this, I don’t have time to handle big issues. So you guys need to learn to figure out stuff TOGETHER. Small issues like this are perfect to practice that shared decisionmaking process. Then we grow to bigger and bigger issues.

**Comment by pxpm** [comment]
Ok ... So looking at what @tabacitu did in the past, I would do like the following:

- Move the `Forgot Password` link under the password field. 
- Remove all `tabindex`s to let browser freely navigate the elements on page as expected. 

The order will become:
`Email > Password > Remember > Forgot > Login`

**Comment by maurohmartinez** [comment]
Ok guys, I don't have much to say tbh since on such small forms (only two fields) I use the mouse/trackpad to get myself around 😆

To me, expecting the tab key to guess/meet my (and everyone's else) intentions is impossible. Perhaps I've been let down by the tab key too often in the past (due to poor html design) that I don't trust it anymore. I don't want to get hurt again...

With that being said, I am happy to change this based on @pxpm suggestions. For the sake of those who do use tab key on this form! ❤️

**Comment by maurohmartinez** [comment]
> accessibility

Good point @pxpm!
Thanks.

**Comment by maurohmartinez** [comment]
@pedro I went ahead and applied the changes we discussed.
Let me know what you think.

Thanks!

https://github.com/Laravel-Backpack/theme-tabler/pull/41
https://github.com/Laravel-Backpack/demo/pull/508

**Comment by pxpm** [comment]
Thanks @maurohmartinez I think it works for now 🙏
