### ISSUE TITLE
Light/Dark theme switcher implementation

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/theme-tabler#33]
It seems the same code is repeatead in alot of files:
![image](https://user-images.githubusercontent.com/7188159/235751104-85d4d70c-aea8-4faf-897f-749d4d56da73.png)

I was about to suggest to don't use use an anchor when we should be using a button, [click here to see why](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#onclick_events), and when searching on what file I should do the suggestion I saw this repeated in all those files. 

This needs clean up IMO, otherwise it will be a nightmare to maintain if it ever need to change.

**Comment by promatik** [comment]
@pxpm I'm happy to say this is now fixed in #61 🙌
That PR moves all the theme buttons to the same blade file, and it uses `<button>` elements 🎉
