### ISSUE TITLE
[Bug] input shadows light/dark theme

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/theme-tabler#34]
There is a big difference in input shadows in light and dark mode. They seem two different themes:

![image](https://user-images.githubusercontent.com/7188159/236245866-fd980db1-b007-4552-8ee8-8496d38bb5b9.png)

![image](https://user-images.githubusercontent.com/7188159/236245976-6bfc4650-2c13-490a-8c5f-172bdce718cc.png)

**Comment by promatik** [comment]
https://github.com/Laravel-Backpack/theme-tabler/pull/102 fixes this one 🙌
