### ISSUE TITLE
[Bug] Remove vertical/horizontal conditionals sidebar file 

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/theme-tabler#36]
# Bug report

Inside the demo we are doing stuff depending on whether the layout is horizontal or vertical. That shouldn't be done by the developer (in sidebar_content), it should be done by the theme.

So let's:
- [x] hide the separators using CSS, if the menu items are shown in a horizontal menu
- [x] use JS to do `data-bs-auto-close` when the menu items are vertical

**Comment by maurohmartinez** [comment]
These should close it:
https://github.com/Laravel-Backpack/demo/pull/506
https://github.com/Laravel-Backpack/theme-tabler/pull/39
