### ISSUE TITLE
text size mismatch between create / update pages

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/theme-tabler#43]
On create:
![image](https://github.com/Laravel-Backpack/theme-tabler/assets/7188159/f2efb849-3351-4899-8747-60058efb6a92)

On update:
![image](https://github.com/Laravel-Backpack/theme-tabler/assets/7188159/5add9942-f879-4809-aebc-4cf9c0282e34)

**Comment by maurohmartinez** [comment]
This, and many other small things, are fixed in a few PR waiting to be merged :)

**Comment by promatik** [comment]
Confirmed it's fixed, I'll close this one 👌
