### ISSUE TITLE
[Bug] Icon_picker field doesn't work

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/theme-tabler#44]
# Bug report

### What I did

Go to our Demo, in Monsters.

### What I expected to happen

Icon_picker field to look good and work.

### What happened

It does not look good, does not work at all:

![CleanShot 2023-05-15 at 15 22 16](https://github.com/Laravel-Backpack/theme-tabler/assets/1032474/a088a781-bd02-4cba-a78f-a6bd1f21ae5b)

### What I've already tried to fix it

Nothing. I thought it was a Bootstrap v5 problem but Mauro has investigated a bit: https://github.com/Laravel-Backpack/theme-tabler/issues/35#issuecomment-1541564269

It looks like the problem is isolated to Tabler. Both CoreUIv4 and Tabler use BS5 but... this field is only broken in Tabler. So... no idea what the problem might be. Maybe some overlapping CSS?!

**Comment by pxpm** [comment]
This is a real mess: 
![image](https://github.com/Laravel-Backpack/theme-tabler/assets/7188159/ee64a472-e28f-49c8-aa9f-af936237a17d)

It required changing files in `icon-picker.js` library just to display like this. 

Not fully tested, but is this a direction we want to follow ? Maintain our own `icon-picker.js` file ? 

Cheers

**Comment by tabacitu** [comment]
We have another issue for this, Pedro is on it.
