### ISSUE TITLE
[Bug] Call to undefined function backpack_theme_config()

### ISSUE THREAD

**Issue by alexanderthegreat96** [Laravel-Backpack/theme-tabler#48]
I just installed it and this is what comes up. 

I am using backpack 5.6

**Comment by pxpm** [comment]
Hello @alexanderthegreat96 there is no way to use this with Backpack v5 sorry. 😢 

You would need to install v6, that we plan to launch in a few weeks. 

We will be releasing it as beta version a week or two before the official launch, so if you want to get grip on the upcoming features without waiting for the final release you can subscribe to our newsletter and/or watch the `Backpack/CRUD` repo to get the updated news about it. 

I am closing this, I hope that we don't need to re-open it when we launch v6, it would be a bad sign 👍 

Thanks for understanding.

Cheers

**Comment by alexanderthegreat96** [comment]
I understand. Thank you.
