### ISSUE TITLE
[Bug] Dark Mode color tweaks required.

### ISSUE THREAD

**Issue by karandatwani92** [Laravel-Backpack/theme-tabler#53]
@tabacitu and I noticed a few things on the dark mode's color palette and we reached here.

- [ ] Primary color for dark mode is missing on `colors.css` turning buttons and every other component blue(the tabler's default)
- [ ] Tune the background color to more black than purple. Try to find an ideal background color that people wouldn't need to change. So if one has a new project, and wants to change the admin panel colors to match branding, he wouldn't need to change the background, only the accent color.

@maurohmartinez You are the right person to do it perfectly. we need your help here!!
Please cover this. Thanks

![image](https://cdn.discordapp.com/attachments/1024243165772914759/1113387651077243032/chrome-capture-2023-4-31.gif)

**Comment by tabacitu** [comment]
Actually we shouldn't ask @maurohmartinez for fixes any more. He's working on the videos (doing a SPECTACULAR job at it) so we want his brain on that alone. Anybody else can pick this up! FREE FOR ALL!

**Comment by karandatwani92** [comment]
OK, @tabacitu. I tried it myself by changing the colors but realized a change in the background would also require changes in another colour config to look seamless. Who else in the team do you think would fit perfectly for such design and theme-related tasks cuz I knew him only...

**Comment by tabacitu** [comment]
Fixed by Antonio in https://github.com/Laravel-Backpack/theme-tabler/pull/87
