### ISSUE TITLE
[v6][Bug] Padding not correctly on CRUD errors

### ISSUE THREAD

**Issue by jorgetwgroup** [Laravel-Backpack/theme-tabler#63]
![245645646-5da8b199-26a1-44d4-b3be-6fd46432dec5](https://github.com/Laravel-Backpack/CRUD/assets/44643608/5d5e640b-5fe9-474a-b8ce-3488212dd3d7)

Padding on form error message look super close to the bottom and left a lot of padding on top.

**Comment by promatik** [comment]
Fix on CRUD; https://github.com/Laravel-Backpack/CRUD/pull/5154
