### ISSUE TITLE
[v6][Bug] Table headings have different font-size in header and footer

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/theme-tabler#64]
Reported by Pedro: Column titles use different sizes in header and in footer. I think we should use the footer size on header too.

![](https://user-images.githubusercontent.com/7188159/246490821-e315d92f-548c-4cc3-9c14-2317f0d865c0.png)

**Comment by promatik** [comment]
Fixed by https://github.com/Laravel-Backpack/theme-tabler/pull/102
