### ISSUE TITLE
Install command, or specific command that publishes config file

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/theme-tabler#67]
I’ve installed a fresh L10 + BPv6. First thing I wanted to do was change the layout from vertical to horizontal, but… I couldn’t easily do that, because the config file wasn’t published for me. Nor did I find a publish command on Github to quickly do that 😔 What I did in the end was to run “php artisan vendor:publish” and choose the Backpack\ThemeTabler\AddonServiceProvider, but that published 3 things - config (good), views (very bad) and assets (bad). We must publish the theme config file on installation, and provide docs for publishing each of the publishable things alone.

So what I think we should do is either:
- (A) instruct people to copy-paste a publish command that only publishes the Theme-Tabler config file, after they install Theme-Tabler
- (B) create a `php artisan backpack:theme-tabler:install` command that does the above

I think A is enough for now. It's just a change in docs, and a change in Backpack's own Install command to do it there too.

We should also do the same for the other themes, if they have config files (document they the way to only publish the config file).

**Comment by pxpm** [comment]
Done, submitted the needed PRs linked above ☝️
