### ISSUE TITLE
[v6][Bug] Getting Started widget looks broken

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/theme-tabler#69]
I’m following the instructions in the Getting Started widget, but the code blocks look broken. A good chunk of text is yellow on white which is unreadable. Switching to dark mode doesn’t fix the problem either - quite the contrary, then it’s obvious the code blocks don’t cater to dark mode at all 😔

We have to polish this widget to look good on all themes we have. It's the first interaction a developer has with Backpack - we can't offer a bad UX or design here.

**Comment by jorgetwgroup** [comment]
Fix with this PR: https://github.com/Laravel-Backpack/theme-tabler/pull/81
