### ISSUE TITLE
[v6][Bug] List view needs a little polish

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/theme-tabler#70]
I’ve created a new Users CRUD, and I’m looking at the ListOperation in Theme-Tabler and… the table looks a bit odd:
- [x] The first heading row is not the same color as the last one
- [x] The table uses 3 shades of grey (first heading row, odd rows, even rows)
- [x] The heading texts don’t really stand out; the text is greyed out and yes it’s capitalized but… it’s smaller than the table body text;
- [x] The “items per page” select looks unstyled;
- [x] The next and previous buttons in pagination look like < and > texts, instead of carets (icons); but I guess it's ok, it's always been this way;
- [x] The search bar isn’t rounded and... since it has no search icon either... it’s not intuitive that it’s a search bar; I suggest we round the corners;
- [x] The search bar, when clicked, has a blue hue (not purple); this is true for all inputs on theme-tabler, and it bothers me; it doesn’t look intentional, but an oversight; actually I think ALL inputs have a blue blue instead of purple, when clicked - the CRUD fields too; 

<img width="1452" alt="CleanShot 2023-06-20 at 17 36 42@2x" src="https://github.com/Laravel-Backpack/theme-tabler/assets/1032474/8c18dca5-ce25-400d-ae9c-d5fbb83f2130">

**Comment by promatik** [comment]
https://github.com/Laravel-Backpack/theme-tabler/pull/102 😌
