### ISSUE TITLE
[Bug] Getting Started widget typo and location

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/theme-tabler#71]
The getting started widget is instructing me in step 4 to change the config in base.php file but it should be ui.php file. Then I noticed this widget is provided by the theme… which… is wrong. It should be provided by CRUD. I see more files in theme-tabler views/inc that should be moved to CRUD - alerts, widgets… maybe… I don’t know…

**Comment by phpfour** [comment]
Hi @tabacitu, we are loading the `dashboard.blade.php` file from the themes which in turn loads the `inc\getting_started.blade.php` file within the theme. 

When you say `It should be provided by CRUD` – do you mean moving both these files (along with necessary dependents) to CRUD?

**Comment by tabacitu** [comment]
Yes

**Comment by phpfour** [comment]
Hey @tabacitu

We are good to move the dashboard view and the getting started widget to the CRUD. I have made sure that the toggles work in all three themes and the styling is consistent (as much as possible).

**Screenshots:** 

![CleanShot 2023-06-29-16 35 16](https://github.com/Laravel-Backpack/theme-tabler/assets/171715/32a511e9-de6c-4c56-83b1-7719adfa4e9b)

![CleanShot 2023-06-29-16 35 47](https://github.com/Laravel-Backpack/theme-tabler/assets/171715/3d81e52e-4f91-4cf2-a3f1-bfd52e23a0e1)

![CleanShot 2023-06-29-16 36 15](https://github.com/Laravel-Backpack/theme-tabler/assets/171715/a26939ea-c1af-4cbb-b3a5-e6af67a6d5fb)
_(yes, I've noticed the gravatar issue – will open a separate PR for that)_

**PRs:**

https://github.com/Laravel-Backpack/CRUD/pull/5150
https://github.com/Laravel-Backpack/theme-tabler/pull/88
https://github.com/Laravel-Backpack/theme-coreuiv4/pull/27
https://github.com/Laravel-Backpack/theme-coreuiv2/pull/16

Let me know if you have any views. 

Thanks!

**Comment by tabacitu** [comment]
Awesome! Thank you @phpfour , they're all merged now 🎉
