### ISSUE TITLE
[v6][Bug] Make user profile image circle instead of rounded-corner-square

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/theme-tabler#73]
In Tabler theme (both light and dark), when using the horizontal layout (but others should have the same), the top-right corner shows the user image and name. The user image is square with rounded corners right now… but I think circles are much better to represent user profile images. First, faces look good in circles because both faces and circles are round. Second, to me at least, if I see a circle image, I assume that’s a user profile pic, because that’s what social media has gotten me used to think. So having it as circle might be a small intuitive clue that the image is for the user.

**Comment by promatik** [comment]
I'll close this one since it's already a circle 👌 not sure when and who did it 😅

**Comment by tabacitu** [comment]
![pick-me-season-10-gif-by-rupauls-drag-race](https://github.com/Laravel-Backpack/theme-tabler/assets/1032474/7ae7647b-465e-4093-b2f0-9bff06006d47)
