### ISSUE TITLE
[v6][Bug] doubleTopBarInHorizontalLayouts squishes and unaligns the logo text in the menu bar

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/theme-tabler#75]
In Tabler theme, when using the horizontal layout with “doubleTopBarInHorizontalLayouts” set to false, the menubar logo gets smaller and squished when it’s a text, so it’s no longer aligned with the menu items. I don’t know if I mind it being smaller, that might actually be better. But it should be aligned with the menu items (vertically), otherwise it looks like a bug.

**Comment by tabacitu** [comment]
Rephrased: In a fresh new Laravel project with Backpack v6 installed and the Tabler theme, I've change the tabler config file to use the `horizontal` layout. So I went from this:

<img width="1512" alt="CleanShot 2023-06-26 at 20 57 53@2x" src="https://github.com/Laravel-Backpack/theme-tabler/assets/1032474/862f7ee9-4e11-4ddb-8746-fd60d76dc0ed">

To this:

<img width="1512" alt="CleanShot 2023-06-26 at 20 58 15@2x" src="https://github.com/Laravel-Backpack/theme-tabler/assets/1032474/676bbdbd-b421-415d-9ee8-a2ae0611a4d9">

All good so far, looking nice. 

BUT when I go in the config file and change `doubleTopBarInHorizontalLayouts` to `false`, it will merge the two top bars (good) but it will also squish the text and raise it, so it's no longer aligned with the menu items:

![CleanShot 2023-06-26 at 20 59 45@2x](https://github.com/Laravel-Backpack/theme-tabler/assets/1032474/ca4ed585-9b42-49de-b9e5-78a68f78ff41)

**Comment by jorgetwgroup** [comment]
Fixed with: https://github.com/Laravel-Backpack/theme-tabler/pull/82

**Comment by tabacitu** [comment]
Let's move the conversation to https://github.com/Laravel-Backpack/theme-tabler/pull/82 then
