### ISSUE TITLE
[v6][Bug] no space between some button icons and text

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/theme-tabler#76]
In DevTools when using Tabler theme, when looking at the ListOperation in Models, some buttons don’t have any space between the button icon and the button text. Perhaps we should implement a margin for icons in buttons, across all buttons. See the Build All CRUDs top button and the See Files line button.

**Comment by promatik** [comment]
Added https://github.com/Laravel-Backpack/DevTools/pull/345 to fix this.

Some icons were wrapped in a span, others don't. Now everything is the same way, so same behaviour everywhere 👌
