### ISSUE TITLE
Theme Tabler started throwing error on every request.

### ISSUE THREAD

**Issue by karandatwani92** [Laravel-Backpack/theme-tabler#91]
### Error being logged on every request:
`Could not find config key: classes.body. Neither in the Backpack theme, nor in the fallback theme, nor in ui.`

![Screenshot 2023-06-30 at 7 42 00 PM](https://github.com/Laravel-Backpack/theme-tabler/assets/8214221/fd6197cf-ee17-4ba3-aa43-7a5917fb7ef2)

**Comment by tabacitu** [comment]
Good catch Karan! Fixed in https://github.com/Laravel-Backpack/theme-tabler/pull/92
