### ISSUE TITLE
Filter button color and text is white when active in light mode and using Tabler

### ISSUE THREAD

**Issue by malle-pietje** [Laravel-Backpack/theme-tabler#98]
# Bug report

### What I did

After upgrade to 6.0 and switching to the Tabler theme this happens for regular CRUD filters

### What I expected to happen

Same behaviour as with dark-mode; button text is visible

### What happened

Light mode:
![image](https://github.com/Laravel-Backpack/CRUD/assets/12016131/174b0c31-5018-49e8-9203-1bd321856473)

Dark mode:
![image](https://github.com/Laravel-Backpack/CRUD/assets/12016131/97b11ae3-93e4-4a74-a727-78994e434fb6)

### What I've already tried to fix it

Nothing

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug is still there.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.2.3 (cli) (built: Feb 14 2023 16:58:12) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.3, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
10.14.1.0

### BACKPACK PACKAGE VERSIONS:
backpack/backupmanager: v5.0.0
backpack/basset: 1.0.0
backpack/crud: 6.0.1
backpack/devtools: 2.0.2
backpack/editable-columns: 3.0.0
backpack/filemanager: 3.0.1
backpack/generators: v4.0.0
backpack/logmanager: v5.0.0
backpack/permissionmanager: 7.0.0
backpack/pro: 2.0.4
backpack/revise-operation: 2.0.0
backpack/settings: 3.1.0
backpack/theme-coreuiv2: 1.1.0
backpack/theme-coreuiv4: 1.0.0
backpack/theme-tabler: 1.0.1

**Comment by malle-pietje** [comment]
Also need to add this only appears to happen with this setting in the `theme-tabler.php` config file:
```
'layout' => 'horizontal_overlap',
```

**Comment by promatik** [comment]
Fixed by #102 👌
